config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :events
  resources :rsvps, only: [:create]

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_many :rsvps, foreign_key: :attended_event_id
  has_many :attendees, through: :rsvps, dependent: :destroy

  scope :past, -> { where("date < ?", Time.now) }
  scope :upcoming, -> { where("date > ?", Time.now) }
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event", dependent: :destroy

  has_many :rsvps, foreign_key: :attendee_id
  has_many :attended_events, through: :rsvps, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role_id, :username])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    if user_signed_in?
      @event = current_user.created_events.create(event_params)
      render :show, status: :created
    else
      redirect_to new_user_session_path, alert: "You must be signed in to create an event"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Event deleted"
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date)
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  def create
    if user_signed_in?
      @event = Event.find(params[:event_id])

      redirect_to event_path(@event), notice: "You have already attended this event" and return if currently_attending?

      current_user.attended_events << @event
      redirect_to root_path, notice: "rsvp successful!"
    else
      redirect_to new_user_session_path, alert: "You must be signed in to attend this event"
    end
  end

  private

  def currently_attending?
    current_user.attended_events.include?(@event)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @events = Event.where(creator_id: params[:id])
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>
<h2>Past Events</h2>
<ul>
  <% Event.past.each do |event| %>
    <li><%= link_to "#{event.name}", event_path(id: event.id) %></li>
  <% end %>
</ul>
<h2>Upcoming Events</h2>
<ul>
  <% Event.upcoming.each do |event| %>
    <li><%= link_to "#{event.name}", event_path(id: event.id) %></li>
  <% end %>
</ul>

<%= link_to "Create an event today!", new_event_path %>

app/views/events/new.html.erb
<h1>Create Your Event</h1>
<%= form_with(model: @event) do |form| %>
  <% if @event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this @event from being saved:</h2>

      <ul>
        <% @event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<h1>This Event</h1>
<%= render partial: "shared/event_info", locals: {events: [@event]} %>

<h2>Who's going</h2>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.username %></li>
  <% end %>
</ul>

<br>
<br>
<%= button_to "Attend this event", rsvps_path, params: { event_id: @event.id } %>
<% if current_user == @event.creator%>
  <%= button_to "Destroy this event", { action: "destroy", id: @event.id }, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <% if user_signed_in? %>
      <%= link_to "My events", user_path(id: current_user.id) %>
    <% end %>
    <%= link_to "Back to front page", root_path %>
  </body>
</html>

app/views/shared/_event_info.html.erb
<% events.each do |event| %>
  <% creator = User.where(id: event.creator_id).pluck(:username).pop %>
  
  <p><%= event.name %></p>
  <p>Time: <%= event.date %></p>
  <p>Location: <%= event.location %></p>
  <p>Organizer: <%= creator %></p>

  <%= link_to "Event details", event_path(event) %>
<% end %>

app/views/users/show.html.erb
<h1>My Events</h1>

<h2>Created Events</h2>
<%= render partial: "shared/event_info", locals: {events: @events} %>

<br>
<h2>Attended Events</h2>
<h3>Past Events</h3>
<% past_events = @user.attended_events.where("date < ?", Time.now) %>
<ul>
  <% past_events.each do |attended_event| %>
    <li><%= link_to "#{attended_event.name}", event_path(id: attended_event.id)  %></li>
  <% end %>
</ul>
<h3>Upcoming Events</h3>
<% future_events = @user.attended_events.where("date > ?", Time.now)%>
<ul>
  <% future_events.each do |attended_event| %>
    <li><%= link_to "#{attended_event.name}", event_path(id: attended_event.id) %></li>
  <% end %>
</ul>